base_url = "https://poetry.linasdev.com"
compile_sass = true
build_search_index = true
# theme = "after-dark"
taxonomies = [
    {name = "languages", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = false

[extra]
author = "Linas NikiperaviÄius"
after_dark_title = "Poetry"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/languages", name = "Languages"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
